### PR TITLE
Add an `all done` deploy command

### PR DESCRIPTION
**Pull request by CaAlden**
I added an `all done` command which completes all items a user has at the front of the queue.

1. It's got a lot of overlap with `dequeueUser` but for the time being I just left it copy-pasted.
2. I tried to write tests for it but running `yarn test` explodes for a bunch of reasons. I started trying to fix them but it seems like quite the can of worms. Am I don't something wrong?
**Edit**: I should clarify, it' explodes for a bunch of reasons unrelated to what I changed. There are a ton of `jshint` errors and `jscs:src` is failing to build. It never even gets to running the tests.

### CODE REVIEW

**Comment by thatsmydoing** [comment]
I think that's mostly from using newer ES syntax. We never really updated the dependencies for that. And even after upgrading and removing the lint step, it still trips up with the syntax so :shrug:

**Review by thatsmydoing — APPROVED** [review]
LGTM

**Comment by CaAlden** [comment]
> I think that's mostly from using newer ES syntax. We never really updated the dependencies for that. And even after upgrading and removing the lint step, it still trips up with the syntax so 🤷

Yeah it was kind of my sense that maybe the grunt stuff wasn't being used.

**Comment by CaAlden** [comment]
How do we go about releasing? Do I just merge and magic happens? (I assume not haha).

**Comment by thatsmydoing** [comment]
If by magic you mean I do stuff, then yeah just merge it.

**Comment by CaAlden** [comment]
> If by magic you mean I do stuff, then yeah just merge it.

Well, that is like magic to me. But I was thinking there might be some sort of `.git` folder with hooks in it that fire after a merge. This would also require a different remote besides `origin`.

**Pull request merged**
